version: 1
update_configs:
  - package_manager: javascript
    directory: '/'
    update_schedule: 'weekly'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'all'
    allowed_updates:
      - match:
          update_type: 'security'
      - match:
          dependency_type: 'production'
          update_type: 'all'
    default_reviewers:
      - ajunajunajun
      - haribote
      - isoden
      - NaokiMatsuda
      - oti
