version: 1
update_configs:
  - package_manager: javascript
    directory: '/'
    update_schedule: 'weekly'
    allowed_updates:
      - match:
          update_type: 'security'
      - match:
          update_type: 'all'
          dependency_type: 'direct'
    default_reviewers:
      - ajunajunajun
      - haribote
      - isoden
      - NaokiMatsuda
      - oti
