name: Pre-Merge

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: pre-process to merge

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: npm install, lint, type-check, and test
        run: |
          npm ci
          npm run lint
          npx tsc --noEmit
          npm test -- --ci
        env:
          CI: true
